project_iteration2/Models/publicart.cs
namespace project_iteration2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("publicart")]
    public partial class publicart
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        public string Gallery_Name { get; set; }

        public double? Latitude { get; set; }

        public double? Longitude { get; set; }

        public string Monday { get; set; }

        public string Tuesday { get; set; }

        public string Wednesday { get; set; }

        public string Thursday { get; set; }

        public string Friday { get; set; }

        public string Saturday { get; set; }

        public string Sunday { get; set; }

        [StringLength(50)]
        public string Opening { get; set; }

        [StringLength(50)]
        public string Painting { get; set; }

        [StringLength(50)]
        public string Sculpture { get; set; }

        [StringLength(50)]
        public string Photography { get; set; }

        [StringLength(50)]
        public string Installation { get; set; }

        [StringLength(50)]
        public string Performance { get; set; }

        [StringLength(50)]
        public string Visual { get; set; }

        [StringLength(50)]
        public string Unisex { get; set; }

        [Column("Toilet ")]
        public string Toilet_ { get; set; }

        public string Gallery_Type { get; set; }

        
        public string Website { get; set; }

        public string Street { get; set; }

        public int? NoOFCF { get; set; }

        public int? NoOfBsn { get; set; }

        public int? NoOfArt { get; set; }

        public int? MonPed { get; set; }

        public int? TuesPed { get; set; }

        public int? WedPed { get; set; }

        public int? ThursPed { get; set; }

        public int? FriPed { get; set; }

        public int? SatPed { get; set; }

        public int? SunPed { get; set; }

        public int? Parking { get; set; }
        public int? MonPed2 { get; set; }

        public int? TuesPed2 { get; set; }

        public int? WedPed2 { get; set; }

        public int? ThursPed2 { get; set; }

        public int? FriPed2 { get; set; }

        public int? SatPed2 { get; set; }

        public int? SunPed2 { get; set; }
        public int? MonPed3 { get; set; }

        public int? TuesPed3 { get; set; }

        public int? WedPed3 { get; set; }

        public int? ThursPed3 { get; set; }

        public int? FriPed3 { get; set; }

        public int? SatPed3 { get; set; }

        public int? SunPed3 { get; set; }


    }
}

project_iteration2/Controllers/publicartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using project_iteration2.Models;
using PagedList;

namespace project_iteration2.Controllers
{
    public class publicartsController : Controller
    {
        private publicartv1 db = new publicartv1();

        public ActionResult compare2(string? option1, string? option2)
        {
            var options = from m in db.publicarts select m;
            var option1Lst = new List<string>();
            var option1Qry = from o in db.publicarts orderby o.Gallery_Name select o.Gallery_Name;
            option1Lst.AddRange(option1Qry.Distinct());
            ViewBag.option1 = new SelectList(option1Lst);

            var option2Lst = new List<string>();
            var option2Qry = from p in db.publicarts orderby p.Gallery_Name select p.Gallery_Name;
            option2Lst.AddRange(option2Qry.Distinct());
            ViewBag.option2 = new SelectList(option2Lst);

            
            if (!string.IsNullOrEmpty(option1) && !string.IsNullOrEmpty(option2))
            {
                options = options.Where(x => x.Gallery_Name == option1 || x.Gallery_Name == option2);
            }
            return View(options.ToList());

        }

        public ActionResult compare(int? id, string option1, string option2)
        {
            var option1Lst = new List<string>();
            var option1Qry = from o in db.publicarts orderby o.Gallery_Name select o.Gallery_Name;
            option1Lst.AddRange(option1Qry.Distinct());
            ViewBag.option1 = new SelectList(option1Lst);
            var option2Lst = new List<string>();
            var option2Qry = from p in db.publicarts orderby p.Gallery_Name select p.Gallery_Name;
            option2Lst.AddRange(option2Qry.Distinct());
            ViewBag.option2 = new SelectList(option2Lst);

            var green = from q in db.publicarts where q.Id == id select q.Gallery_Name;

            ViewBag.showSomething = green;

            var options = from m in db.publicarts select m;
            
            if (!string.IsNullOrEmpty(option1) && !string.IsNullOrEmpty(option2))
            {
                options = options.Where(x => x.Gallery_Name == option1 || x.Gallery_Name == option2);
            }

            //if (!string.IsNullOrEmpty(option2))
            //{
            //    options = options.Where(y => y.Gallery_Name == option2);
            //}
            System.Diagnostics.Debug.WriteLine(options.ToList().Count);
            return View(options.ToList());
        }
        // GET: publicarts
        public ViewResult Index(string sortOrder,int? page, string currentFilter, bool? toilet, bool? install, bool? visual, bool? perf,bool? photography, bool? sculpture, bool? painting,string GallType ,string street , string searchString)
        {
            
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Gallery_Name" : "";
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentAcc = toilet;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var dropDownType = new List<string>();
            var dropDownTypeQry = from t in db.publicarts
                orderby t.Gallery_Type
                select t.Gallery_Type;
            dropDownType.AddRange(dropDownTypeQry.Distinct());
            ViewBag.GallType = new SelectList(dropDownType);
            var dropDownListStreet = new List<string>();
            var streetQry = from d in db.publicarts orderby d.Street select d.Street;
            dropDownListStreet.AddRange(streetQry.Distinct());
            ViewBag.street = new SelectList(dropDownListStreet);
            var publictemp = from s in db.publicarts
                select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                publictemp = publictemp.Where(s => s.Gallery_Name.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(street))
            {
                publictemp = publictemp.Where(x => x.Street == street);
            }
            if (!string.IsNullOrEmpty(GallType))
            {
                publictemp = publictemp.Where(x => x.Gallery_Type == GallType);
            }

            if (sculpture == true)

            {
                publictemp = publictemp.Where(s => s.Sculpture.Contains("Y"));
            }
            if (photography == true)

            {
                publictemp = publictemp.Where(s => s.Photography.Contains("Y"));
            }

            if (perf == true)
            {
                publictemp = publictemp.Where(s => s.Performance.Contains("Y"));
            }

            if ( painting == true)
            {
                publictemp = publictemp.Where(s => s.Painting.Contains("Y"));
            }
            if (install == true)
            {
                publictemp = publictemp.Where(s => s.Installation.Contains("Y"));
            }
            if (visual == true)
            {
                publictemp = publictemp.Where(s => s.Visual.Contains("Y"));
            }
            if (toilet == true)
            {
                publictemp = publictemp.Where(s => s.Unisex.Contains("Y"));
            }

            switch (sortOrder)
            {
                default:
                    publictemp = publictemp.OrderBy(s => s.Gallery_Name);
                    break;
            }

          



            return View(publictemp.ToList());
        }

        // GET: publicarts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            publicart publicart = db.publicarts.Find(id);
            if (publicart == null)
            {
                return HttpNotFound();
            }
            return View(publicart);
        }

        // GET: publicarts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: publicarts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Gallery_Name,Latitude,Longitude,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Opening,Painting,Sculpture,Photography,Installation,Performance,Visual,Unisex,Toilet_,Gallery_Type,Description,Website,Street")] publicart publicart)
        {
            if (ModelState.IsValid)
            {
                db.publicarts.Add(publicart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(publicart);
        }

        // GET: publicarts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            publicart publicart = db.publicarts.Find(id);
            if (publicart == null)
            {
                return HttpNotFound();
            }
            return View(publicart);
        }

        // POST: publicarts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Gallery_Name,Latitude,Longitude,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Opening,Painting,Sculpture,Photography,Installation,Performance,Visual,Unisex,Toilet_,Gallery_Type,Website,Street,NoOFCF,NoOfBsn,NoOfArt, MonPed, TuesPed, WedPed, ThursPed, FriPed, SatPed, SunPed, Parking,MonPed2,TuesPed2,WedPed2,ThursPed2,FriPed2,SatPed2,SunPed2,MonPed3,TuesPed3,WedPed3,ThursPed3,FriPed3,SatPed3,SunPed3")] publicart publicart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publicart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publicart);
        }

        // GET: publicarts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            publicart publicart = db.publicarts.Find(id);
            if (publicart == null)
            {
                return HttpNotFound();
            }
            return View(publicart);
        }

        // POST: publicarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            publicart publicart = db.publicarts.Find(id);
            db.publicarts.Remove(publicart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

project_iteration2/Views/publicarts/Delete.cshtml
@model project_iteration2.Models.publicart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>publicart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gallery_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gallery_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tuesday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tuesday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wednesday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wednesday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thursday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thursday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Friday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Friday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Saturday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Saturday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sunday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sunday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opening)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opening)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Painting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Painting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sculpture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sculpture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photography)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Installation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Installation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Performance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Performance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unisex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unisex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Toilet_)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Toilet_)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gallery_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gallery_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

project_iteration2/Views/publicarts/Index.cshtml
@model IEnumerable<project_iteration2.Models.publicart>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<style>



    html {
        width: 100%;
    }

    .card {
        /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        position: relative;
    }
    .card:hover{
        transform:scale(1.2);
        background:lightgrey;
    }

        /* On mouse-over, add a deeper shadow */
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

    /* Add some padding inside the card container */
    .container {
        padding: 2px 16px;
    }

    .button {
        border-radius: 4px;
        background-color: #d8c4af;
        border: none;
        color: #FFFFFF;
        text-align: center;
        font-size: 20px;
        padding: 5px;
        width: 100px;
        transition: all 0.5s;
        cursor: pointer;
        margin: 5px;
        left: 87%;
        position: relative;
    }

    #img {
        position: fixed;
        width: 100%;
        height: 100px;
    }

    label {
        position: absolute;
        top: 0;
        left: 0
    }

    input#show, input#hide {
        display: none;
    }

    span#content {
        display: block;
        -webkit-transition: opacity 1s ease-out;
        transition: opacity 1s ease-out;
        opacity: 0;
        height: 0;
        font-size: 0;
        overflow: hidden;
    }

    input#show:checked ~ .show:before {
        content: ""
    }

    input#show:checked ~ .hide:before {
        content: "Hide"
    }

    input#hide:checked ~ .hide:before {
        content: ""
    }

    input#hide:checked ~ .show:before {
        content: "Show"
    }

    input#show:checked ~ span#content {
        opacity: 1;
        font-size: 100%;
        height: auto;
    }

    input#hide:checked ~ span#content {
        display: block;
        -webkit-transition: opacity 1s ease-out;
        transition: opacity 1s ease-out;
        opacity: 0;
        height: 0;
        font-size: 0;
        overflow: hidden;
    }

    #show1 {
        position: absolute;
        top: 20px;
        left: 0
    }

    #content1 {
        display: block;
        -webkit-transition: opacity 1s ease-out;
        transition: opacity 1s ease-out;
        opacity: 0;
        height: 0;
        font-size: 0;
        overflow: hidden;
    }

    #show1:before {
        content: "Show"
    }

    #show1:active.show1:before {
        content: "Hide"
    }

    #show1:active ~ span#content1 {
        opacity: 1;
        font-size: 100%;
        height: auto;
    }




    /* extra */
    #content, #content1, #content2 {
        float: left;
        margin: 100px auto;
    }
    .hidden {
        visibility: hidden;
    }

    .unhidden {
        visibility: visible;
    } 
    .drop1 , .drop2 {
        font-size:12px;
    }

</style>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("GALLEVISIONERY", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    @Html.ActionLink("BACK", "Index", "Home")
                </li>
            </ul>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <img style="width:100%; height: 300px; margin-top:40px  ;" src="~/Content/bannerNew.jpg" />

    </div>
</div>

<hr />
<div class="row">
    @using (Html.BeginForm("Index","publicarts", FormMethod.Get))
    {<div class="md-form">
         <p>
                 Search By Name 
                 @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                 
           
                 Gallery Region @Html.DropDownList("street", null, "Choose one", new { @class = "btn dropdown-toggle drop1" })


                 Gallery Type @Html.DropDownList("GallType", null, "Choose one", new { @class = "btn dropdown-toggle drop2" })

             @*<label class="btn btn-light" style="position: relative; padding:10px; margin:5px;">
                 @Html.CheckBox("toilet", false, new { @class = "custom-control-input" } ) <b>Accesible Toilets</b>
             </label>*@
             
                 <input type="submit" value="Search" class="btn btn-dark" style="position:static; float: right; margin-top:20px; margin-right:10%;" />
             
             <br />
                 <br />
                 <a href="javascript:unhide('hideDiv');">TYPE OF ART</a>
                 <div id="hideDiv" class="hidden" style="position:static;">
                     <div class="form-group">

                         <div class="btn-group">
                             <div class="row">
                                 <div class="col-sm-3" style="padding:10px; width: auto; left:40%">
                                     <label class="btn btn-light" style="position: static; left:40%;">
                                         @Html.CheckBox("painting", false) <b>painting</b>
                                     </label>
                                 </div>
                                 <div class="col-sm-3" style="padding:10px; width: auto; left:50%;">
                                     <label class="btn btn-light" style="position: static; left:50%;">
                                         @Html.CheckBox("sculpture", false) <b>Sculpture</b>
                                     </label>
                                 </div>
                                 <div class="col-sm-3" style="padding:10px; width: auto; left: 60%;">
                                     <label class="btn btn-light" style="position: static; left:60%;">
                                         @Html.CheckBox("perf", false)<b>
                                             Performing Arts
                                         </b>
                                     </label>
                                 </div>
                             

                                 <div class="col-sm-3" style="padding:10px; width: auto; left:70%;">
                                     <label class="btn btn-light " style="position: static; left:70%;">
                                         @Html.CheckBox("photography", false) <b>Photography</b>
                                     </label>
                                 </div>
                             </div>
                             <div class="row">
                                 <div class="col-sm-6" style="padding:10px; width: auto; left:70%;">
                                     <label class="btn btn-light" style="position: static; left:70%;">
                                         @Html.CheckBox("install", false) <b>Installation</b>
                                     </label>
                                 </div>
                                 <div class="col-sm-6" style="padding:10px; width: auto; left:80%;">
                                     <label class="btn btn-light" style="position: static; left:80%;">
                                         @Html.CheckBox("visual", false) <b>Visual Arts</b>
                                     </label>
                                 </div>
                             </div>
                         </div>

                     </div>
                 </div>




</p>
        </div>
    }
    <hr />
</div>

@foreach (var item in Model)

{
<div class="col-md-4">
    <a href="~/publicarts/Details/@item.Id"  data-toggle="popover" data-trigger="hover" data-content="Some content">
    <div class="card" style="margin: 20px; width: 30rem; height: 250px;">
        <img class="card-img-top" src="~/Content/picture/@item.Id/image1.jpg" style="width: 100%; height: 150px;">
        <div class="card-body">
            <h4 class="card-subtitle" style="padding-left: 20px; padding-top: 10px; color:black;"> <b> @Html.DisplayFor(modelItem => item.Gallery_Name, new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })</b></h4>

            <div style=" position: absolute; padding-bottom: 10px; padding-left:20px; margin:0; ">
                @Html.ActionLink("Details", "Details", "publicarts", new { id = item.Id }, new { @class = "btn btn-dark " })
                
            
                @Html.ActionLink("Compare", "compare", "publicarts", new { id = item.Id }, new { @class = "btn btn-dark " })

            </div>
        </div>
    </div></a>
</div>
}
    <br/>
 

<script>
    function unhide(divID) {
        var item = document.getElementById(divID);
        if (item) {
            item.className=(item.className=='hidden')?'unhidden':'hidden';
        }
    }
</script>